---
version: "3"
services:
  risingwave-standalone:
    extends:
      file: ../../docker/docker-compose.yml
      service: risingwave-standalone
  etcd-0:
    extends:
      file: ../../docker/docker-compose.yml
      service: etcd-0
  grafana-0:
    extends:
      file: ../../docker/docker-compose.yml
      service: grafana-0
  minio-0:
    extends:
      file: ../../docker/docker-compose.yml
      service: minio-0
  prometheus-0:
    extends:
      file: ../../docker/docker-compose.yml
      service: prometheus-0
  trino:
    image: trinodb/trino:418
    container_name: trino
    volumes:
      - ./etc/risingwave.properties:/etc/trino/catalog/risingwave.properties
    ports:
      - "48080:8080"
  trino-client:
    image: trinodb/trino:418
    profiles: [ "client" ]
    entrypoint: [ "trino", "--server", "trino:8080", "--catalog", "risingwave", "--schema", "public" ]
  presto:
    image: ahanaio/prestodb-sandbox
    container_name: presto
    volumes:
      - ./etc/risingwave.properties:/opt/presto-server/etc/catalog/risingwave.properties
    ports:
      - "8080:8080"
  presto-client:
    image: ahanaio/prestodb-sandbox
    profiles: [ "client" ]
    entrypoint: [ "presto-cli", "--server", "presto:8080", "--catalog", "risingwave", "--schema", "public" ]
volumes:
  risingwave-standalone:
    external: false
  etcd-0:
    external: false
  grafana-0:
    external: false
  minio-0:
    external: false
  prometheus-0:
    external: false
name: risingwave-compose
