[package]
name = "risingwave_pb"
version = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[dependencies]
enum-as-inner = "0.6"
pbjson = "0.6"
prost = { workspace = true }
prost-helpers = { path = "helpers" }
risingwave_error = { workspace = true }
serde = { version = "1", features = ["derive"] }
strum = "0.25"
thiserror = "1"
tonic = { workspace = true }

[target.'cfg(not(madsim))'.dependencies]
workspace-hack = { path = "../workspace-hack" }

[build-dependencies]
fs-err = "2.11"
pbjson-build = "0.5"
tonic-build = { workspace = true }
walkdir = "2"

[package.metadata.cargo-machete]
ignored = ["workspace-hack"]

[package.metadata.cargo-udeps.ignore]
normal = ["workspace-hack"]

[lints]
workspace = true
