[package]
name = "workspace-config"
version = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
# some crates opt-in static linking, while some opt-in dynamic linking,
# so they are two features :)
rw-static-link = ["openssl-sys", "sasl2-sys"]
rw-dynamic-link = ["zstd-sys"]

[dependencies]
log = { version = "0.4", features = ["release_max_level_debug"] }
openssl-sys = { version = "0.9.96", optional = true, features = ["vendored"] }
sasl2-sys = { version = "0.1", optional = true, features = ["gssapi-vendored"] }
tracing = { version = "0.1", features = ["release_max_level_debug"] }
zstd-sys = { version = "2", optional = true, default-features = false, features = ["pkg-config"] }
# workspace-hack = { path = "../../workspace-hack" }
# Don't add workspace-hack into this crate!

# FIXME(xxchan): This is a temporary fix due to how cargo and hakari works. See related PR for more details.
# We will revisit how to handle workspace-hack and build-dependency issues later.
[build-dependencies]
openssl-sys = { version = "0.9.96", optional = true, features = ["vendored"] }

[lints]
workspace = true
